[package]
name = "rosalind-cli"
version = "0.0.1"
authors = ["Anton Klimenko <antklim@gmail.com>"]

[dependencies]
getopts = "0.2"
rosalind = {git = "https://github.com/antklim/rosalind.git", version = "0.0.1"}
